### ISSUE TITLE
Kotlin codegen fails when an inline fragment's implementation is in a fragment 

### ISSUE THREAD

**Issue by ekarasabun** [apollographql/apollo-android#1676]
Assume we have a `fragment` definition and its usage inside an `inline fragment` as below:

```
fragment mySectionFragment on MySection {
    id
    text
    ....
}

query myQuery() {
  myQuery() {
    sections {
      ... on MySection {
        ...mySectionFragment
      }
    }
  }
}
```
where `sections` is an interface and `MySection` is one possible implementation that we're interested in.

Java codegen is able to correctly generate `sections().get(0).fragments().mySection()`, however Kotlin codegen is unable to generate any code for `sections[0].inlineFragment.mySection`. Essentially `.mySection` is missing in the Kotlin generated code.

**Comment by TonnyL** [comment]
I got the same error (https://github.com/apollographql/apollo-android/issues/1657), try the latest version, it was solved 🎉.

**Comment by jporcelli-tt** [comment]
Im still seeing this. Im not sure the structure is exactly the same

**Comment by jporcelli-tt** [comment]
Thank you!
