### ISSUE TITLE
New codegen does not generate mapper types for interface implementations

### ISSUE THREAD

**Issue by gshcherb** [apollographql/apollo-android#1721]
Suppose you have a graphql interface and it's implementations like:

```
 {
          "kind": "INTERFACE",
          "name": "PriceHistory",
          "fields": [
               ...
          ],
          "inputFields": null,
          "interfaces": null,
          "enumValues": null,
          "possibleTypes": [
            {
              "kind": "OBJECT",
              "name": "PriceHistoryStandard",
              "ofType": null
            },
            {
              "kind": "OBJECT",
              "name": "PriceHistoryChange",
              "ofType": null
            }
          ]
        }
}
```

old codegen inside of the appropriate mapper was generating mappers for all permutations

```
final AsPriceHistoryStandard.Mapper asPriceHistoryStandard = new AsPriceHistoryStandard.Mapper();
final AsPriceHistoryChange.Mapper asPriceHistoryChange = new AsPriceHistoryChangeMapper();
final AsPriceHistory.Mapper asPriceHistoryFieldMapper = new AsPriceHistory.Mapper();
```

new codegen ignores all the implementations.

**Comment by sav007** [comment]
Could you please try the latest release 1.2.1, I believe it was addressed?

**Comment by gshcherb** [comment]
Sorry, but still see this with 1.2.1

I also see some interesting errors like:
```Can't parse `Array` value, expected array```
and
```
Field `boundingBox`(217:4) and `boundingBox`(217:4) conflicts because they have different schema types. Use different aliases on the fields to fetch both.
```
but they are probably not related, though they all complain about invalid types.

**Comment by sav007** [comment]
Super strange we have exactly the same test fixture:
https://github.com/apollographql/apollo-android/blob/master/apollo-compiler/src/test/graphql/com/example/simple_inline_fragment/TestQuery.java

where:
```
{
          "kind": "INTERFACE",
          "name": "Character",
          "description": "A character from the Star Wars universe",
          "inputFields": null,
          "interfaces": null,
          "enumValues": null,
          "possibleTypes": [
            {
              "kind": "OBJECT",
              "name": "Human",
              "ofType": null
            },
            {
              "kind": "OBJECT",
              "name": "Droid",
              "ofType": null
            }
          ]
        }
```

Is there any way I can take a look at your query and schema?

**Comment by gshcherb** [comment]
Thanks for posting this sample. The difference between new and old codegen is: old one allowed to explicitly specify inline fragment for the type you query fields on. Code from sample works for both new and old codegens, but code below works only for old one. I actually like new one better and not sure it needs to be fixed, but reporting here just for clarity.

{code}
query TestQuery {
    hero {
        ... on Character {
            name
            ... on Human {
                height
            }
            ... on Droid {
                primaryFunction
            }
        }
    }
}
{code}

**Comment by gshcherb** [comment]
Array parsing message clarified here https://github.com/apollographql/apollo-android/issues/1731

**Comment by melashkov** [comment]
> Super strange we have exactly the same test fixture:
> https://github.com/apollographql/apollo-android/blob/master/apollo-compiler/src/test/graphql/com/example/simple_inline_fragment/TestQuery.java
> 
> where:
> 
> ```
> {
>           "kind": "INTERFACE",
>           "name": "Character",
>           "description": "A character from the Star Wars universe",
>           "inputFields": null,
>           "interfaces": null,
>           "enumValues": null,
>           "possibleTypes": [
>             {
>               "kind": "OBJECT",
>               "name": "Human",
>               "ofType": null
>             },
>             {
>               "kind": "OBJECT",
>               "name": "Droid",
>               "ofType": null
>             }
>           ]
>         }
> ```
> 
> Is there any way I can take a look at your query and schema?

Would like to know what is the best way to access those height and primaryFunction fields?

**Comment by gshcherb** [comment]
@melashkov there is a query in the samples. Take a look here https://github.com/apollographql/apollo-android/blob/master/apollo-compiler/src/test/graphql/com/example/simple_inline_fragment/TestOperation.graphql

**Comment by sav007** [comment]
Hey folks I'm a little lost here. Should we close this issue?

```
query TestQuery {
    hero {
        ... on Character {
```

New codegen recognizes that `hero` has `Character`  type so it merges fields and removes unnecessary inline fragment `.. on Character ` (it doesn't make sense as `hero` already `Character`).

**Comment by gshcherb** [comment]
Yes, but if you define the inline fragment it does **not** generate `As*` types for other inline fragments. This is a difference between old and new codegens, but I think this is not critical and just worth to know for those who will migrate to new one. Unless the goal is to make new codegen producing exactly the same code that old one did, this issue can be closed.
